# Generated by Django 5.1.5 on 2025-01-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(error_messages={'unique': 'Um usuário com este número de matrícula já está cadastrado.'}, help_text='Seu número de matrícula do SUAP ou SIAPE. Apenas números.', max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='matricula'),
        ),
    ]
