# Generated by Django 5.0.1 on 2025-03-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Um usuário com este email já está cadastrado.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
