# Generated by Django 5.2.6 on 2025-09-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_condicionado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcondicionado',
            name='temperatura',
        ),
        migrations.AddField(
            model_name='arcondicionado',
            name='sala',
            field=models.CharField(default='sala nao registrada', max_length=100),
            preserve_default=False,
        ),
    ]
